server:
  port: 8080

    #logging:
    #level:
    #root: INFO
    #org.springframework.web: INFO
  #org.springframework.security: INFO

jdbc:
  url: jdbc:mysql://localhost:3306/mengxi
  username: root
  password: 123456
  driver-class-name: com.mysql.cj.jdbc.Driver
  type: com.alibaba.druid.pool.DruidDataSource

spring:
  profiles:
    active: dev
  #thymeleaf模版配置
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
  #mysql 连接配置
  datasource:
    url: jdbc:mysql://localhost:3306/mengxi
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
  main:
    allow-bean-definition-overriding: true
  #redis连接配置
  redis:
    host: localhost
    port: 6379

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.shiro.demo.entity

shiro:
  #userNativeSessionManager: true
  #loginUrl: /login
  #sessionManager:
    #sessionIdUrlRewritingEnabled: false
  unauthorizedUrl: /unauthorized

elasticsearch:
  #serverUrl: http://es-cn-nwy3crg6e000hf5f7.public.elasticsearch.aliyuncs.com:9200
  serverUrl: http://es-cn-wwo3dffsg0006er3e.public.elasticsearch.aliyuncs.com:9200
  #apiKey: cF9SZWJvb0I4SFd3UW5EN3pwbEc6S1JKR2tXMGlSNktJTjVpSUU2YjdJUQ==
  apiKey: QU9XeGM0b0JTeC1nTlhnNVFLdjM6UXVKaWhPVHNTa21GT09SY05xNkVxdw==


